//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Xml.Serialization;

namespace Northwind.Entities
{
	[Serializable]
	[XmlInclude(typeof(Product))]
	[SoapInclude(typeof(Product))]
	public class AbstractCategory
	{
		public virtual int CategoryID { get; set; }

		public virtual string CategoryName { get; set; }

		public virtual string Description { get; set; }

		public virtual byte[] Picture { get; set; }

		public virtual IList Products { get; set; }
	}

	[Serializable]
	public class Category : AbstractCategory
	{
	}
}