//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Northwind.Entities
{
	[Serializable]
	public class AbstractCustomerCustomerDemo
	{
		public virtual CustomerCustomerDemoKey PK_CustomerCustomerDemo { get; set; }

		#region Nested type: CustomerCustomerDemoKey

		[Serializable]
		public class CustomerCustomerDemoKey
		{
			public virtual CustomerDemographic CustomerDemographic { get; set; }

			public virtual Customer Customer { get; set; }

			public override int GetHashCode()
			{
				return base.GetHashCode();
			}

			public override bool Equals(object obj)
			{
				if (((obj == null)
					 || (obj == DBNull.Value)))
				{
					return false;
				}
				var entity = ((CustomerCustomerDemoKey)(obj));
				return ((CustomerDemographic == entity.CustomerDemographic)
						&& (Customer == entity.Customer));
			}
		}

		#endregion
	}

	[Serializable]
	public class CustomerCustomerDemo : AbstractCustomerCustomerDemo
	{
	}
}