//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Northwind.Entities
{
	[Serializable]
	public class AbstractEmployeeTerritory
	{
		public virtual EmployeeTerritoryKey PK_EmployeeTerritories { get; set; }

		#region Nested type: EmployeeTerritoryKey

		[Serializable]
		public class EmployeeTerritoryKey
		{
			public virtual Employee Employee { get; set; }

			public virtual Territory Territory { get; set; }

			public override int GetHashCode()
			{
				return base.GetHashCode();
			}

			public override bool Equals(object obj)
			{
				if (((obj == null)
					 || (obj == DBNull.Value)))
				{
					return false;
				}
				var entity = ((EmployeeTerritoryKey)(obj));
				return ((Employee == entity.Employee)
						&& (Territory == entity.Territory));
			}
		}

		#endregion
	}

	[Serializable]
	public class EmployeeTerritory : AbstractEmployeeTerritory
	{
	}
}