//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Xml.Serialization;

namespace Northwind.Entities
{
	[Serializable]
	[XmlInclude(typeof(OrderDetail))]
	[SoapInclude(typeof(OrderDetail))]
	public class AbstractProduct
	{
		public virtual int ProductID { get; set; }

		public virtual bool Discontinued { get; set; }

		public virtual string ProductName { get; set; }

		public virtual string QuantityPerUnit { get; set; }

		[SoapElement(IsNullable = true)]
		public virtual Int16? ReorderLevel { get; set; }

		[SoapElement(IsNullable = true)]
		public virtual Decimal? UnitPrice { get; set; }

		[SoapElement(IsNullable = true)]
		public virtual Int16? UnitsInStock { get; set; }

		[SoapElement(IsNullable = true)]
		public virtual Int16? UnitsOnOrder { get; set; }

		public virtual Category Category { get; set; }

		public virtual IList OrderDetails { get; set; }

		public virtual Supplier Supplier { get; set; }
	}

	[Serializable]
	public class Product : AbstractProduct
	{
	}
}