//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Xml.Serialization;

namespace Northwind.Entities
{
	[Serializable]
	[XmlInclude(typeof(Territory))]
	[SoapInclude(typeof(Territory))]
	public class AbstractRegion
	{
		public virtual int RegionID { get; set; }

		public virtual string RegionDescription { get; set; }

		public virtual IList Territories { get; set; }
	}

	[Serializable]
	public class Region : AbstractRegion
	{
	}
}