//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoCanHelpMe.Infrastructure.News.Configuration
{
	/// <summary>
	/// A collection of SearchTag instances.
	/// </summary>
	[global::System.Configuration.ConfigurationCollection(typeof(global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag), CollectionType = global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName = global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTags.SearchTagPropertyName)]
	public partial class SearchTags : global::System.Configuration.ConfigurationElementCollection
	{
		#region Constants
		
		/// <summary>
		/// The XML name of the individual <see cref="global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag"/> instances in this collection.
		/// </summary>
		internal const global::System.String SearchTagPropertyName = "searchTag";

		#endregion

		#region Overrides

		/// <summary>
		/// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
		/// </summary>
		/// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
		public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
		{
			get
			{
				return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
			}
		}

		/// <summary>
		/// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
		/// </summary>
		/// <param name="elementName">The name of the element to verify.</param>
		/// <returns>
		/// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>. The default is <see langword="false"/>.
		/// </returns>
		protected override global::System.Boolean IsElementName(global::System.String elementName)
		{
			return (elementName == SearchTagPropertyName);
		}

		/// <summary>
		/// Gets the element key for a specified configuration element when overridden in a derived class.
		/// </summary>
		/// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
		/// <returns>
		/// An <see cref="global::System.Object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
		/// </returns>
		protected override global::System.Object GetElementKey(global::System.Configuration.ConfigurationElement element)
		{
			return ((global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag)element).Name;
		}

		/// <summary>
		/// When overridden in a derived class, creates a new <see cref="global::System.Configuration.ConfigurationElement"/>.
		/// </summary>
		/// <returns>
		/// A new <see cref="global::System.Configuration.ConfigurationElement"/>.
		/// </returns>
		protected override global::System.Configuration.ConfigurationElement CreateNewElement()
		{
			return new global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag();
		}

		#endregion
		
		#region Indexer

		/// <summary>
		/// Gets the <see cref="global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag"/> at the specified index.
		/// </summary>
		/// <param name="index">The index of the <see cref="global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag"/> to retrieve</param>
		public global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag this[int index]
		{
			get
			{
				return (global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag)this.BaseGet(index);
			}
		}

		#endregion
		
		#region Add

		/// <summary>
		/// Adds the specified <see cref="global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag"/>.
		/// </summary>
		/// <param name="searchTag">The <see cref="global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag"/> to add.</param>
		public void Add(global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag searchTag)
		{
			base.BaseAdd(searchTag);
		}

		#endregion
		
		#region Remove

		/// <summary>
		/// Removes the specified <see cref="global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag"/>.
		/// </summary>
		/// <param name="searchTag">The <see cref="global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag"/> to remove.</param>
		public void Remove(global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTag searchTag)
		{
			base.BaseRemove(searchTag);
		}

		#endregion
	}
}

namespace WhoCanHelpMe.Infrastructure.News.Configuration
{
	/// <summary>
	/// The SearchTag Configuration Element.
	/// </summary>
	public partial class SearchTag : global::System.Configuration.ConfigurationElement
	{
		#region Name Property
		
		/// <summary>
		/// The XML name of the <see cref="Name"/> property.
		/// </summary>
		internal const global::System.String NamePropertyName = "name";
		
		/// <summary>
		/// Gets or sets the Name.
		/// </summary>
		[global::System.Configuration.ConfigurationProperty(NamePropertyName, IsRequired = true, IsKey = true, IsDefaultCollection = false)]
		public global::System.String Name
		{
			get
			{
				return (global::System.String)base[NamePropertyName];
			}
			set
			{
				base[NamePropertyName] = value;
			}
		}
		
		#endregion

	}
}

namespace WhoCanHelpMe.Infrastructure.News.Configuration
{
	/// <summary>
	/// The NewsConfigurationSection Configuration Section.
	/// </summary>
	public partial class NewsConfigurationSection : global::System.Configuration.ConfigurationSection
	{
		#region NoOfBuzzHeadlines Property
		
		/// <summary>
		/// The XML name of the <see cref="NoOfBuzzHeadlines"/> property.
		/// </summary>
		internal const global::System.String NoOfBuzzHeadlinesPropertyName = "noOfBuzzHeadlines";
		
		/// <summary>
		/// Gets or sets the NoOfBuzzHeadlines.
		/// </summary>
		[global::System.Configuration.ConfigurationProperty(NoOfBuzzHeadlinesPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false, DefaultValue = 7)]
		public global::System.Int32 NoOfBuzzHeadlines
		{
			get
			{
				return (global::System.Int32)base[NoOfBuzzHeadlinesPropertyName];
			}
			set
			{
				base[NoOfBuzzHeadlinesPropertyName] = value;
			}
		}
		
		#endregion

		#region SearchTimeoutSeconds Property
		
		/// <summary>
		/// The XML name of the <see cref="SearchTimeoutSeconds"/> property.
		/// </summary>
		internal const global::System.String SearchTimeoutSecondsPropertyName = "searchTimeoutSeconds";
		
		/// <summary>
		/// Gets or sets the SearchTimeoutSeconds.
		/// </summary>
		[global::System.Configuration.ConfigurationProperty(SearchTimeoutSecondsPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false, DefaultValue = 10)]
		public global::System.Int32 SearchTimeoutSeconds
		{
			get
			{
				return (global::System.Int32)base[SearchTimeoutSecondsPropertyName];
			}
			set
			{
				base[SearchTimeoutSecondsPropertyName] = value;
			}
		}
		
		#endregion

		#region NoOfDevTeamHeadlines Property
		
		/// <summary>
		/// The XML name of the <see cref="NoOfDevTeamHeadlines"/> property.
		/// </summary>
		internal const global::System.String NoOfDevTeamHeadlinesPropertyName = "noOfDevTeamHeadlines";
		
		/// <summary>
		/// Gets or sets the NoOfDevTeamHeadlines.
		/// </summary>
		[global::System.Configuration.ConfigurationProperty(NoOfDevTeamHeadlinesPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false, DefaultValue = 7)]
		public global::System.Int32 NoOfDevTeamHeadlines
		{
			get
			{
				return (global::System.Int32)base[NoOfDevTeamHeadlinesPropertyName];
			}
			set
			{
				base[NoOfDevTeamHeadlinesPropertyName] = value;
			}
		}
		
		#endregion

		#region BuzzHeadlineTags Property
		
		/// <summary>
		/// The XML name of the <see cref="BuzzHeadlineTags"/> property.
		/// </summary>
		internal const global::System.String BuzzHeadlineTagsPropertyName = "buzzHeadlineTags";
		
		/// <summary>
		/// Gets or sets the BuzzHeadlineTags.
		/// </summary>
		[global::System.Configuration.ConfigurationProperty(BuzzHeadlineTagsPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
		public global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTags BuzzHeadlineTags
		{
			get
			{
				return (global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTags)base[BuzzHeadlineTagsPropertyName];
			}
			set
			{
				base[BuzzHeadlineTagsPropertyName] = value;
			}
		}
		
		#endregion

		#region DevTeamHeadlineTags Property
		
		/// <summary>
		/// The XML name of the <see cref="DevTeamHeadlineTags"/> property.
		/// </summary>
		internal const global::System.String DevTeamHeadlineTagsPropertyName = "devTeamHeadlineTags";
		
		/// <summary>
		/// Gets or sets the DevTeamHeadlineTags.
		/// </summary>
		[global::System.Configuration.ConfigurationProperty(DevTeamHeadlineTagsPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
		public global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTags DevTeamHeadlineTags
		{
			get
			{
				return (global::WhoCanHelpMe.Infrastructure.News.Configuration.SearchTags)base[DevTeamHeadlineTagsPropertyName];
			}
			set
			{
				base[DevTeamHeadlineTagsPropertyName] = value;
			}
		}
		
		#endregion

		#region Singleton Instance

		/// <summary>
		/// The XML name of the NewsConfigurationSection Configuration Section.
		/// </summary>
		internal const global::System.String NewsConfigurationSectionSectionName = "newsConfigurationSection";

		/// <summary>
		/// Gets the NewsConfigurationSection instance.
		/// </summary>
		public static global::WhoCanHelpMe.Infrastructure.News.Configuration.NewsConfigurationSection Instance
		{
			get
			{
				return global::System.Configuration.ConfigurationManager.GetSection(NewsConfigurationSectionSectionName) as global::WhoCanHelpMe.Infrastructure.News.Configuration.NewsConfigurationSection;
			}
		}

		#endregion

		#region Xmlns Property
		
		/// <summary>
		/// The XML name of the <see cref="Xmlns"/> property.
		/// </summary>
		internal const global::System.String XmlnsPropertyName = "xmlns";
		
		/// <summary>
		/// Gets the XML namespace of this Configuration Section.
		/// </summary>
		/// <remarks>
		/// This property makes sure that if the configuration file contains the XML namespace,
		/// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
		/// </remarks>
		[global::System.Configuration.ConfigurationProperty(XmlnsPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
		public global::System.String Xmlns
		{
			get
			{
				return (global::System.String)base[XmlnsPropertyName];
			}
		}
		
		#endregion
	}
}

