//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

namespace MSpecTests.WhoCanHelpMe.Web.Controllers
{
    using System.Web.Mvc;
    using System.Web.Routing;
    using global::WhoCanHelpMe.Domain.Cms.Pages;
    using global::WhoCanHelpMe.Web.Controllers;
    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;
    using Machine.Specifications.Mvc;

    public abstract class context_for_n2_controller : Specification<N2Controller<HomePage>>
    {
        Establish context = () =>
            {
                var routeData = new RouteData();
                routeData.Values.Add("n2_item", new HomePage { Name = "Home Page" });

                subject.ControllerContext = new ControllerContext() { RouteData = routeData };
            };
    }

    [Subject(typeof(N2Controller<>))]
    public class when_the_n2_controller_is_asked_for_the_default_action : context_for_n2_controller
    {
        static ActionResult result;

        Because of = () => result = subject.Index();

        It should_return_the_default_view = () =>
            result.ShouldBeAView().And().ShouldUseDefaultView();

        It should_use_the_default_master_page = () =>
            result.ShouldBeAView().And().MasterName.ShouldEqual("Site");

        It should_populate_the_view_model_with_the_current_item_from_the_cms = () =>
            result.Model<HomePage>().Name.ShouldEqual("Home Page");
    }
}