CREATE TABLE [dbo].[n2DetailCollection] (
    [ID]     INT           IDENTITY (1, 1) NOT NULL,
    [ItemID] INT           NULL,
    [Name]   NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

