//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoCanHelpMe.Infrastructure.Analytics.Configuration
{
	/// <summary>
	/// The AnalyticsConfigurationSection Configuration Section.
	/// </summary>
	public partial class AnalyticsConfigurationSection : global::System.Configuration.ConfigurationSection
	{
		#region AnalyticsIdentifier Property
		
		/// <summary>
		/// The XML name of the <see cref="AnalyticsIdentifier"/> property.
		/// </summary>
		internal const global::System.String AnalyticsIdentifierPropertyName = "analyticsIdentifier";
        /// <summary>
		/// The XML name of the <see cref="SiteVerification"/> property.
		/// </summary>
        internal const global::System.String SiteVerificationPropertyName = "siteVerification";
		
		/// <summary>
		/// Gets or sets the AnalyticsIdentifier.
		/// </summary>
		[global::System.Configuration.ConfigurationProperty(AnalyticsIdentifierPropertyName, IsRequired = true, IsKey = false, IsDefaultCollection = false)]
		public global::System.String AnalyticsIdentifier
		{
			get
			{
				return (global::System.String)base[AnalyticsIdentifierPropertyName];
			}
			set
			{
				base[AnalyticsIdentifierPropertyName] = value;
			}
		}

        /// <summary>
        /// Gets or sets the SiteVerification.
        /// </summary>
        [global::System.Configuration.ConfigurationProperty(SiteVerificationPropertyName, IsRequired = true, IsKey = false, IsDefaultCollection = false)]
        public global::System.String SiteVerification
        {
            get
            {
                return (global::System.String)base[SiteVerificationPropertyName];
            }
            set
            {
                base[SiteVerificationPropertyName] = value;
            }
        }
		
		#endregion

		#region Singleton Instance

		/// <summary>
		/// The XML name of the AnalyticsConfigurationSection Configuration Section.
		/// </summary>
		internal const global::System.String AnalyticsConfigurationSectionSectionName = "analyticsConfigurationSection";

		/// <summary>
		/// Gets the AnalyticsConfigurationSection instance.
		/// </summary>
		public static global::WhoCanHelpMe.Infrastructure.Analytics.Configuration.AnalyticsConfigurationSection Instance
		{
			get
			{
				return global::System.Configuration.ConfigurationManager.GetSection(AnalyticsConfigurationSectionSectionName) as global::WhoCanHelpMe.Infrastructure.Analytics.Configuration.AnalyticsConfigurationSection;
			}
		}

		#endregion

		#region Xmlns Property
		
		/// <summary>
		/// The XML name of the <see cref="Xmlns"/> property.
		/// </summary>
		internal const global::System.String XmlnsPropertyName = "xmlns";
		
		/// <summary>
		/// Gets the XML namespace of this Configuration Section.
		/// </summary>
		/// <remarks>
		/// This property makes sure that if the configuration file contains the XML namespace,
		/// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
		/// </remarks>
		[global::System.Configuration.ConfigurationProperty(XmlnsPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
		public global::System.String Xmlns
		{
			get
			{
				return (global::System.String)base[XmlnsPropertyName];
			}
		}
		
		#endregion
	}
}

